### ISSUE TITLE
Retain State and Battery level after black-out

### ISSUE THREAD

**Issue by SmartM-ui** [shogunxam/ESP32_BLETracker#34]
Hi,
would it be possible to implement a retain on the home / not home state and on the last battery level?

If I'm not mistaken, after a blackout, if the NUT is out of the house, the values are "unknown"

Thanks

**Comment by shogunxam** [comment]
I'm not quite sure enabling the retain on the state of the device is a good idea. In example take a look to this sequence:
1. your BLE device is at home and discovered
2. there is a power outage
3. you and your BLE Device go out of home
4. the power is restored (you are still out of home)
In this scenario if the retain is enabled  your broker will tell to all the subscribers your device is at home.
What I can do is, only when the white list is enabled, initializing the list of discovered devices with all the devices in the white list, with initial state off so that all the devices not present when the power is restored will be considered off and not "not available".

**Comment by SmartM-ui** [comment]
Hi,
it seems to me a great idea!
