### ISSUE TITLE
Running extremely slow?

### ISSUE THREAD

**Issue by Arakon** [shogunxam/ESP32_BLETracker#54]
I have three ESP32 modules, two Wemos ESP32 Mini 1.0.0 and a generic Wroom one. Whenever I flash the firmware to them, I can access it via the webserver, but most of the time, the website is broken (no background, no boxes, etc, see:
![image](https://user-images.githubusercontent.com/12016360/136648430-23c43867-47ad-4bd0-b54a-5586e2c6c051.png)

It also does not detect any devices, no logs are generated on the log screen, none of the fields get populated. 
I compiled with Arduino 1.8.13, ESP32 library 1.0.4, with the BLE library copied over as instructed.
When enabling serial debug logging, all seems good, the loop runs and shows that it connected to the broker and is sending data.

Any ideas what is going wrong here?

**Comment by shogunxam** [comment]
Hi @Arakon, difficult to say without a log.
Have you already tried to connect one of the three esp32 to the Arduino IDE terminal console in order to get some feedback?
Each esp has to have it's own gateway name, and only ble devices with public Mac address are tracked.
I haven't compiled with Arduino IDE for some time, can you try with PlatformIO?

**Comment by Arakon** [comment]
Alright, that seems indeed to be down to be the Arduino IDE.. I just compiled it with PlatformIO and it runs normally.

**Comment by shogunxam** [comment]
With PlatformIO I'm using a newest esp32 platform with some fix, there are probably some incompatibilities with the library supplied with Arduino IDE. Compiling with PlatformIO is easier because it automatically includes, and downloads, all necessary dependencies. I will mark the part of the documentation related to Arduino IDE as obsolete.
If it's fine for you I'll close this issue.
