### ISSUE TITLE
only battery state ?

### ISSUE THREAD

**Issue by JulienNabaztag** [shogunxam/ESP32_BLETracker#58]
**mqtt logs :**

nabaztag/BLETracker/chambre_enfant/6AC7B6D0DB24 {"state":"off","rssi":-100,"battery":-1}
nabaztag/BLETracker/chambre_enfant/LWT online
nabaztag/BLETracker/chambre_enfant/LWT offline
nabaztag/BLETracker/chambre_enfant/A4C1385292B8 {"state":"off","rssi":-100,"battery":100}
nabaztag/BLETracker/chambre_enfant/A4C13848CC60 {"state":"off","rssi":-100,"battery":100}
nabaztag/BLETracker/chambre_enfant/D8A35C6BF705 {"state":"off","rssi":-100,"battery":-1}
nabaztag/BLETracker/chambre_enfant/7CD1C3369470 {"state":"off","rssi":-100,"battery":-1}

**Hi, it looks be only battery notifications or I did something bad ?**

//Set to true if you want track only the devices in the white list
#define ENABLE_BLE_TRACKER_WHITELIST false

//List of known devices you want track
//Each entry is in the format {"MAC-ADDRESS", read-battery, "Description"} i.e.{"A6B5C4D3E2F1", true, "My iTag"}
//Mac Addresses are in the form "A6B5C4D3E2F1" (uppercase and no separator)
//Each block is coma separated
#define BLE_KNOWN_DEVICES_LIST  {"A4C1385292B8", true, "LYWSD03MMC chambre Gabriel"}, {"A4C13848CC60", true, "LYWSD03MMC chambre parents"}

**these are Hygro thermometer and I would like to get all datas from them**
cf. https://esphome.io/components/sensor/xiaomi_ble.html#lywsd03mmc

**is this feature available? if not maybe I can add it on the code. I just need to know where is it ^^
I get them from python :**

ATC_characteristic_datas = [
    ['00002a1f-0000-1000-8000-00805f9b34fb', 	'int', 10, 'temperature'],
    ['0002a6f-0000-1000-8000-00805f9b34fb', 	'int', 100, 'humidity'],
    ['00002a19-0000-1000-8000-00805f9b34fb', 	'int', 1, 'battery'],
]

**and about iBeacon UUID is it a feature enable ?**

**here my extra configuration :** 

#define LOCATION "nabaztag"
#define GATEWAY_NAME "BLETracker/chambre_enfant"
#define TOPIC_FORMAT 1

//Set to true if you want to enable the iBeacon mode
#define ENABLE_IBEACON true

//iBeacon type
#define IBEACON_TYPE 0x0215

//iBeacon UUID (709ecc6d-2f85-891f-ea42-4a544ca7e2c4)
#define IBEACON_UUID 0x70, 0x9e, 0xcc, 0x6d, 0x2f, 0x85, 0x89, 0x1f, 0xea, 0x42, 0x4a, 0x54, 0x4c, 0xa7, 0xe2, 0xc4

//iBeacon major (etaj)
#define IBEACON_MAJOR 1

//iBeacon minor (piece)
#define IBEACON_MINOR 2

**on espHome I used these parameters :** 

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:52:92:B8" # chambre de Gabriel
    temperature:
      name: "Température 2"
    humidity:
      name: "Humidité 2"
    battery_level:
      name: "Batterie 2"
    signal_strength:
      name: "Signal 2"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:48:CC:60" # chambre des parents
    temperature:
      name: "Température 3"
    humidity:
      name: "Humidité 3"
    battery_level:
      name: "Batterie 3"
    signal_strength:
      name: "Signal 3"
      
**initially i tried this project because i wanted to use "esp32_ble_tracker" and "esp32_ble_beacon" at the same time, esphome doesn't allow that**

esp32_ble_beacon:
    type: iBeacon
    uuid: '709ecc6d-2f85-891f-ea42-4a544ca7e2c4'
    major: 1
    minor: 2

**Comment by shogunxam** [comment]
Hi @JulienNabaztag, thanks for trying my project.
BLE devices, when paired, are undetectable. For this reason it is not possible to determine their presence. In your case I assume the device was detected while it was unpaired and therefore it was possible to read the battery value which is saved for 12h before reading it again, after this period, if the device is not detected, the battery value will be -1. Alternativelly  you have moved the device too far from the ESP32.   
Give a try unparing the device, if it is paired, or move it near the ESP32 to see if something changes.  
In order to read the others values you should implement a function similar to my **batteryLevel** that you find in the main.ino where, from the service_BATT_UUID (0x180F), I read the char_BATT_UUID (0x2A19) characteristic. Obbviously you will have to use appropriate services and characteristics. This link may be useful for you
[Getting Started with ESP32 Bluetooth Low Energy (BLE) on Arduino IDE](https://randomnerdtutorials.com/esp32-bluetooth-low-energy-ble-arduino-ide/) to understand how to use the values you extracted from the python.  
The project does not support iBeacon UUID but recognizes devices only by their mac-address
Regards.
